#!/usr/bin/env python3
"""Generate ``docs/reference/DATABASE_SCHEMA.md`` from a migrated database.

The schema document is read out of PostgreSQL's catalogue, so it describes
what the migrations actually built - columns, types, nullability, defaults,
keys, foreign keys and every index.

Usage (uses the normal DB_* configuration)::

    python3 tools/docs/generate_schema.py            # write
    python3 tools/docs/generate_schema.py --check    # exit 1 if stale

``tests/integration/test_schema_reference.py`` compares the committed file
with a freshly migrated test database.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Dict, List

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / "docs" / "reference" / "DATABASE_SCHEMA.md"

_COLUMNS = """
SELECT table_name, column_name, data_type, is_nullable, column_default,
       character_maximum_length, ordinal_position, is_identity
FROM information_schema.columns
WHERE table_schema = 'public'
ORDER BY table_name, ordinal_position
"""
_CONSTRAINTS = """
SELECT rel.relname, con.conname, con.contype, pg_get_constraintdef(con.oid)
FROM pg_constraint con
JOIN pg_class rel ON rel.oid = con.conrelid
JOIN pg_namespace ns ON ns.oid = rel.relnamespace
WHERE ns.nspname = 'public'
ORDER BY rel.relname, con.contype, con.conname
"""
_INDEXES = """
SELECT tablename, indexname, indexdef FROM pg_indexes
WHERE schemaname = 'public' ORDER BY tablename, indexname
"""
_MIGRATIONS = "SELECT version, name FROM schema_migrations ORDER BY version"

_KIND = {"p": "PRIMARY KEY", "u": "UNIQUE", "f": "FOREIGN KEY", "c": "CHECK"}


def _type(data_type: str, length) -> str:
    return f"{data_type}({length})" if length else data_type


def _default(value) -> str:
    if value is None:
        return ""
    text = str(value)
    if text.startswith("nextval("):
        return "serial"
    return f"`{text}`".replace("|", "\\|")


def render(columns, constraints, indexes, migrations) -> str:
    tables: Dict[str, List] = {}
    for row in columns:
        tables.setdefault(row[0], []).append(row)
    cons: Dict[str, List] = {}
    for table, name, kind, definition in constraints:
        cons.setdefault(table, []).append((name, kind, definition))
    idx: Dict[str, List] = {}
    for table, name, definition in indexes:
        idx.setdefault(table, []).append((name, definition))

    out = ["# Database schema", "",
           "_Generated by `tools/docs/generate_schema.py` from a migrated database; "
           "do not edit by hand. The design is explained in "
           "[../DATABASE.md](../DATABASE.md)._", "",
           f"Migrations applied: {', '.join(f'`{v}` {n}' for v, n in migrations)}.", "",
           f"{len(tables)} tables:", ""]
    out.append(" · ".join(f"[`{t}`](#{t})" for t in sorted(tables)))
    out.append("")
    for table in sorted(tables):
        out += [f"## {table}", "", "| # | Column | Type | Null | Default |",
                "| --- | --- | --- | --- | --- |"]
        for _t, column, data_type, nullable, default, length, pos, identity in tables[table]:
            shown = "identity" if identity == "YES" else _default(default)
            out.append(f"| {pos} | `{column}` | {_type(data_type, length)} | "
                       f"{'yes' if nullable == 'YES' else 'no'} | {shown} |")
        if cons.get(table):
            out += ["", "Constraints:", ""]
            for name, kind, definition in cons[table]:
                out.append(f"- {_KIND.get(kind, kind)} `{name}`: `{definition}`")
        extra = [(n, d) for n, d in idx.get(table, [])
                 if n not in {c[0] for c in cons.get(table, [])}]
        if extra:
            out += ["", "Indexes:", ""]
            for name, definition in extra:
                using = definition.split(" USING ", 1)[-1]
                unique = "unique " if definition.startswith("CREATE UNIQUE") else ""
                out.append(f"- {unique}`{name}` - {using}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def generate(connection) -> str:
    with connection.cursor() as cur:
        results = []
        for sql in (_COLUMNS, _CONSTRAINTS, _INDEXES, _MIGRATIONS):
            cur.execute(sql)
            results.append(cur.fetchall())
    return render(*results)


def _connect():
    import os

    import psycopg2

    sys.path.insert(0, str(ROOT))
    try:
        from dotenv import load_dotenv

        load_dotenv(ROOT / ".env", override=False)
    except ImportError:
        pass
    return psycopg2.connect(host=os.environ.get("DB_HOST", "localhost"),
                            port=int(os.environ.get("DB_PORT", "5432")),
                            user=os.environ.get("DB_USER", "postgres"),
                            password=os.environ.get("DB_PASSWORD", ""),
                            dbname=os.environ.get("DB_NAME", "analysis"))


def main(argv: List[str]) -> int:
    connection = _connect()
    try:
        text = generate(connection)
    finally:
        connection.close()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None
    if "--check" in argv:
        if current != text:
            print(f"{TARGET.relative_to(ROOT)} is stale; run python3 tools/docs/generate_schema.py")
            return 1
        print("schema reference is up to date")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
