#!/usr/bin/env python3
"""Count-aware bandit gate.

Bandit's native `-b` baseline matches findings by file/test/severity/
confidence/message, so a NEW dangerous site in a file that already has a
baseline entry passes the gate silently (recorded limitation, step 25
security audit). This gate closes that hole: it compares the number of
findings per (file, check) against the manifest generated by `--update`,
and fails when any cell grows.

Usage:
    python3 tools/security/bandit_count_gate.py            # enforce
    python3 tools/security/bandit_count_gate.py --update   # regenerate manifest

The manifest is generated ONLY after every new site has been triaged by
hand (parameterized values, allowlisted identifiers, module constants);
growing a cell requires a deliberate `--update` with triage of the new
sites, exactly like the message-level baseline.
"""
from __future__ import annotations

import collections
import json
import subprocess
import sys
from pathlib import Path

MANIFEST = Path(__file__).with_name("bandit-counts.json")
SCAN_CMD = ["bandit", "-q", "-c", "pyproject.toml", "-r", ".", "-ll", "-f", "json"]


def scan() -> dict:
    proc = subprocess.run(SCAN_CMD, capture_output=True, text=True)
    if proc.returncode not in (0, 1):
        sys.stderr.write(proc.stderr[-2000:])
        raise SystemExit(f"bandit scan failed with exit {proc.returncode}")
    return json.loads(proc.stdout)


def counts(report: dict) -> dict:
    cell = collections.Counter()
    for r in report.get("results", []):
        cell[(r["filename"], r["test_id"])] += 1
    return {f"{f}|{t}": n for (f, t), n in sorted(cell.items())}


def main() -> int:
    current = counts(scan())
    if "--update" in sys.argv:
        MANIFEST.write_text(json.dumps(current, indent=1) + "\n")
        print(f"manifest updated: {MANIFEST} ({len(current)} cells)")
        return 0
    baseline = json.loads(MANIFEST.read_text())
    grown = []
    for key, n in current.items():
        if n > baseline.get(key, 0):
            grown.append((key, baseline.get(key, 0), n))
    if grown:
        print("COUNT GATE FAILED: findings grew in baselined cells. "
              "Triage each new site (parameterized values, allowlisted "
              "identifiers, module constants), fix real issues, then "
              "regenerate with --update.")
        for key, b, c in sorted(grown):
            f, t = key.split("|", 1)
            print(f"  {t} {f}: {b} -> {c}")
        return 1
    print(f"count gate OK: no cell exceeds its triaged count "
          f"({len(current)} cells)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
